server:
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        # 카멜케이스 -> 스네이크 케이스로 바꿔주는 전략 ENTITY가 선언한게 스네이크 케이스로 DB생성 됨
        # EX ) counselId => counsel_id
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users\LG\Downloads
logging.level:
  org.hibernate.SQL: debug